/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_5;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
       Scanner scan = new Scanner(System.in);
       System.out.println("Introduzca o soldo fixo:");
       double sf = scan.nextDouble();
       System.out.println("Introduzca o importe total de ventas:");
       double im = scan.nextDouble();
       double iv = im * (5/100);
       System.out.println("Introduzca os kilometros recorridos:");
       double kms = scan.nextDouble();
       double km = kms * 2;
       System.out.println("Introduzca a cantidade de dias de desplazamiento nos que se a requerido de dieta:");
       double dsd = scan.nextDouble();
       double dd = dsd * 30;
       double sb = sf + iv + km + dd;
       double sl = sb - (sb * 0.18 + 36);
       System.out.println("O soldo base e de: " + sb +".\n O soldo líquido e de: " + sl + "." );
    }
}
