/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_4;
 import java.util.Scanner;
public class App {
    
    

    public static void main(String[] args) {
        int euros,nbilletes20,nbilletes100,nbilletes5,nmonedas1;
     Scanner obxScaner = new Scanner (System.in);
     System.out.println("Introduce los euros a cambiar");
     euros= obxScaner.nextInt();
     nbilletes100=euros/100;
     nbilletes20=euros%100/20;
     nbilletes5=euros%100%20/5;
     nmonedas1=euros%100%20%5;
     System.out.println("Os euros son iguais a "+nbilletes100+" billetes de 100 "+nbilletes20+" billetes de 20 "+nbilletes5+" billetes de 5 "+nmonedas1+" monedas de 1 euro");
    }
}
