/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_3;
import java.util.Scanner;
public class App {
    

    public static void main(String[] args) {
        int billete20,billete100,billete5,nbillete20,nbillete100,nbillete5,nmoneda1;
        Scanner obxScaner = new Scanner (System.in);
        System.out.println("Introduce los billetes de 20");
         nbillete20= obxScaner.nextInt();
         billete20=20;
          System.out.println("Introduce los billetes de 100");
        nbillete100= obxScaner.nextInt();
        billete100=100;
         System.out.println("Introduce los billetes de 5");
         nbillete5= obxScaner.nextInt();
         billete5=5;
         System.out.println("Introduce las monedas de 1€");
          nmoneda1= obxScaner.nextInt();
          System.out.println("O total e= "+((nbillete20*billete20)+(nbillete100*billete100)+(nbillete5*billete5)+nmoneda1)+"€");
          
    }
}
